batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 19
model_path: Models\202305211912
train_epochs: 1000
train_workers: 20
vocab: 3y9o).-LBu5*njTt':Y0V2abi#OK"(pgx;r6cQ!vmhP?Cd/GMNEqD7z4FHe1A8RXkw,sUZlJfSWI
width: 128
