batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 19
model_path: Models\202305211836
train_epochs: 1000
train_workers: 20
vocab: 9zp80mMP5(3F.1GYCOg,U/EN-RaeT76njBAdHb'"!2vZcsxW):JD?*woy;Iltq4rkLXuVQKSf#ih
width: 128
